//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.20 at 12:03:27 PM CST 
//


package com.mastercard.api.repower.v1.repower.domain;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RequestId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="TransactionReference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TransactionHistory">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Transaction">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SystemTraceAuditNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="NetworkReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SettlementDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Response">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="SubmitDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AccountBalance">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestId",
    "transactionReference",
    "transactionHistory",
    "accountBalance"
})
@XmlRootElement(name = "Repower")
public class Repower {

    @XmlElement(name = "RequestId", required = true)
    protected BigInteger requestId;
    @XmlElement(name = "TransactionReference", required = true)
    protected String transactionReference;
    @XmlElement(name = "TransactionHistory", required = true)
    protected TransactionHistory transactionHistory;
    @XmlElement(name = "AccountBalance", required = true)
    protected AccountBalance accountBalance;

    /**
     * Gets the value of the requestId property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *     
     */
    public BigInteger getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the requestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setRequestId(BigInteger value) {
        this.requestId = value;
    }

    /**
     * Gets the value of the transactionReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionReference() {
        return transactionReference;
    }

    /**
     * Sets the value of the transactionReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionReference(String value) {
        this.transactionReference = value;
    }

    /**
     * Gets the value of the transactionHistory property.
     * 
     * @return
     *     possible object is
     *     {@link com.mastercard.api.repower.v1.repower.domain.Repower.TransactionHistory }
     *     
     */
    public TransactionHistory getTransactionHistory() {
        return transactionHistory;
    }

    /**
     * Sets the value of the transactionHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.mastercard.api.repower.v1.repower.domain.Repower.TransactionHistory }
     *     
     */
    public void setTransactionHistory(TransactionHistory value) {
        this.transactionHistory = value;
    }

    /**
     * Gets the value of the accountBalance property.
     * 
     * @return
     *     possible object is
     *     {@link com.mastercard.api.repower.v1.repower.domain.Repower.AccountBalance }
     *     
     */
    public AccountBalance getAccountBalance() {
        return accountBalance;
    }

    /**
     * Sets the value of the accountBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.mastercard.api.repower.v1.repower.domain.Repower.AccountBalance }
     *     
     */
    public void setAccountBalance(AccountBalance value) {
        this.accountBalance = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value",
        "currency"
    })
    public static class AccountBalance {

        @XmlElement(name = "Value")
        protected long value;
        @XmlElement(name = "Currency", required = true)
        protected String currency;

        /**
         * Gets the value of the value property.
         * 
         */
        public long getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(long value) {
            this.value = value;
        }

        /**
         * Gets the value of the currency property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurrency() {
            return currency;
        }

        /**
         * Sets the value of the currency property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurrency(String value) {
            this.currency = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Transaction">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SystemTraceAuditNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="NetworkReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SettlementDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Response">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="SubmitDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transaction"
    })
    public static class TransactionHistory {

        @XmlElement(name = "Transaction", required = true)
        protected Transaction transaction;

        /**
         * Gets the value of the transaction property.
         * 
         * @return
         *     possible object is
         *     {@link com.mastercard.api.repower.v1.repower.domain.Repower.TransactionHistory.Transaction }
         *     
         */
        public Transaction getTransaction() {
            return transaction;
        }

        /**
         * Sets the value of the transaction property.
         * 
         * @param value
         *     allowed object is
         *     {@link com.mastercard.api.repower.v1.repower.domain.Repower.TransactionHistory.Transaction }
         *     
         */
        public void setTransaction(Transaction value) {
            this.transaction = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SystemTraceAuditNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="NetworkReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SettlementDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Response">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="SubmitDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "type",
            "systemTraceAuditNumber",
            "networkReferenceNumber",
            "settlementDate",
            "response",
            "submitDateTime"
        })
        public static class Transaction {

            @XmlElement(name = "Type", required = true)
            protected String type;
            @XmlElement(name = "SystemTraceAuditNumber", required = true)
            protected String systemTraceAuditNumber;
            @XmlElement(name = "NetworkReferenceNumber", required = true)
            protected String networkReferenceNumber;
            @XmlElement(name = "SettlementDate", required = true)
            protected String settlementDate;
            @XmlElement(name = "Response", required = true)
            protected Response response;
            @XmlElement(name = "SubmitDateTime", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar submitDateTime;

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the systemTraceAuditNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSystemTraceAuditNumber() {
                return systemTraceAuditNumber;
            }

            /**
             * Sets the value of the systemTraceAuditNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSystemTraceAuditNumber(String value) {
                this.systemTraceAuditNumber = value;
            }

            /**
             * Gets the value of the networkReferenceNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNetworkReferenceNumber() {
                return networkReferenceNumber;
            }

            /**
             * Sets the value of the networkReferenceNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNetworkReferenceNumber(String value) {
                this.networkReferenceNumber = value;
            }

            /**
             * Gets the value of the settlementDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSettlementDate() {
                return settlementDate;
            }

            /**
             * Sets the value of the settlementDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSettlementDate(String value) {
                this.settlementDate = value;
            }

            /**
             * Gets the value of the response property.
             * 
             * @return
             *     possible object is
             *     {@link com.mastercard.api.repower.v1.repower.domain.Repower.TransactionHistory.Transaction.Response }
             *     
             */
            public Response getResponse() {
                return response;
            }

            /**
             * Sets the value of the response property.
             * 
             * @param value
             *     allowed object is
             *     {@link com.mastercard.api.repower.v1.repower.domain.Repower.TransactionHistory.Transaction.Response }
             *     
             */
            public void setResponse(Response value) {
                this.response = value;
            }

            /**
             * Gets the value of the submitDateTime property.
             * 
             * @return
             *     possible object is
             *     {@link javax.xml.datatype.XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getSubmitDateTime() {
                return submitDateTime;
            }

            /**
             * Sets the value of the submitDateTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link javax.xml.datatype.XMLGregorianCalendar }
             *     
             */
            public void setSubmitDateTime(XMLGregorianCalendar value) {
                this.submitDateTime = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "code",
                "description"
            })
            public static class Response {

                @XmlElement(name = "Code", required = true)
                protected String code;
                @XmlElement(name = "Description", required = true)
                protected String description;

                /**
                 * Gets the value of the code property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCode() {
                    return code;
                }

                /**
                 * Sets the value of the code property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCode(String value) {
                    this.code = value;
                }

                /**
                 * Gets the value of the description property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDescription() {
                    return description;
                }

                /**
                 * Sets the value of the description property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDescription(String value) {
                    this.description = value;
                }

            }

        }

    }

}
