//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.16 at 10:31:21 AM CDT 
//


package com.mastercard.api.merchantid.v1.merchantid.domain.factory;

import javax.xml.bind.annotation.XmlRegistry;
import com.mastercard.api.merchantid.v1.merchantid.domain.MerchantIds;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MerchantIds }
     * 
     */
    public MerchantIds createMerchantIds() {
        return new MerchantIds();
    }

    /**
     * Create an instance of {@link MerchantIds.ReturnedMerchants }
     * 
     */
    public MerchantIds.ReturnedMerchants createMerchantIdsReturnedMerchants() {
        return new MerchantIds.ReturnedMerchants();
    }

    /**
     * Create an instance of {@link MerchantIds.ReturnedMerchants.Merchant }
     * 
     */
    public MerchantIds.ReturnedMerchants.Merchant createMerchantIdsReturnedMerchantsMerchant() {
        return new MerchantIds.ReturnedMerchants.Merchant();
    }

    /**
     * Create an instance of {@link MerchantIds.ReturnedMerchants.Merchant.Address }
     * 
     */
    public MerchantIds.ReturnedMerchants.Merchant.Address createMerchantIdsReturnedMerchantsMerchantAddress() {
        return new MerchantIds.ReturnedMerchants.Merchant.Address();
    }

    /**
     * Create an instance of {@link MerchantIds.ReturnedMerchants.Merchant.Address.CountrySubdivision }
     * 
     */
    public MerchantIds.ReturnedMerchants.Merchant.Address.CountrySubdivision createMerchantIdsReturnedMerchantsMerchantAddressCountrySubdivision() {
        return new MerchantIds.ReturnedMerchants.Merchant.Address.CountrySubdivision();
    }

    /**
     * Create an instance of {@link MerchantIds.ReturnedMerchants.Merchant.Address.Country }
     * 
     */
    public MerchantIds.ReturnedMerchants.Merchant.Address.Country createMerchantIdsReturnedMerchantsMerchantAddressCountry() {
        return new MerchantIds.ReturnedMerchants.Merchant.Address.Country();
    }

}
