//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.14 at 09:59:35 AM CDT 
//


package com.mastercard.api.mdes.csrapi.v1.pan.swap.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Response" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="statusCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="statusDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="referenceId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="tokenUniqueId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "response"
})
@XmlRootElement(name = "Responses")
public class Responses {

    @XmlElement(name = "Response", required = true)
    protected List<Response> response;

    /**
     * Gets the value of the response property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the response property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.mastercard.api.mdes.csrapi.v1.pan.swap.domain.Responses.Response }
     * 
     * 
     */
    public List<Response> getResponse() {
        if (response == null) {
            response = new ArrayList<Response>();
        }
        return this.response;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="statusCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="statusDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="referenceId" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="tokenUniqueId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "statusCode",
        "statusDescription",
        "referenceId",
        "tokenUniqueId"
    })
    public static class Response {

        protected int statusCode;
        @XmlElement(required = true)
        protected String statusDescription;
        protected int referenceId;
        @XmlElement(required = true)
        protected String tokenUniqueId;

        /**
         * Gets the value of the statusCode property.
         * 
         */
        public int getStatusCode() {
            return statusCode;
        }

        /**
         * Sets the value of the statusCode property.
         * 
         */
        public void setStatusCode(int value) {
            this.statusCode = value;
        }

        /**
         * Gets the value of the statusDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatusDescription() {
            return statusDescription;
        }

        /**
         * Sets the value of the statusDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatusDescription(String value) {
            this.statusDescription = value;
        }

        /**
         * Gets the value of the referenceId property.
         * 
         */
        public int getReferenceId() {
            return referenceId;
        }

        /**
         * Sets the value of the referenceId property.
         * 
         */
        public void setReferenceId(int value) {
            this.referenceId = value;
        }

        /**
         * Gets the value of the tokenUniqueId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTokenUniqueId() {
            return tokenUniqueId;
        }

        /**
         * Sets the value of the tokenUniqueId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTokenUniqueId(String value) {
            this.tokenUniqueId = value;
        }

    }

}
