//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.18 at 10:46:38 PM CST 
//


package com.mastercard.api.fraud.merchant.v1.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for merchant-match_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="merchant-match_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://mastercard.com/termination}match-enumeration_Type"/>
 *         &lt;element name="DoingBusinessAsName" type="{http://mastercard.com/termination}match-enumeration_Type" minOccurs="0"/>
 *         &lt;element name="PhoneNumber" type="{http://mastercard.com/termination}match-enumeration_Type" minOccurs="0"/>
 *         &lt;element name="Address" type="{http://mastercard.com/termination}match-enumeration_Type"/>
 *         &lt;element name="CountrySubdivisionTaxId" type="{http://mastercard.com/termination}match-enumeration_Type" minOccurs="0"/>
 *         &lt;element name="NationalTaxId" type="{http://mastercard.com/termination}match-enumeration_Type" minOccurs="0"/>
 *         &lt;element name="PrincipalMatch" type="{http://mastercard.com/termination}principal-match_Type" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "merchant-match_Type", propOrder = {
    "name",
    "doingBusinessAsName",
    "phoneNumber",
    "address",
    "countrySubdivisionTaxId",
    "nationalTaxId",
    "principalMatch"
})
public class MerchantMatchType {

    @XmlElement(name = "Name", required = true)
    protected MatchEnumerationType name;
    @XmlElement(name = "DoingBusinessAsName")
    protected MatchEnumerationType doingBusinessAsName;
    @XmlElement(name = "PhoneNumber")
    protected MatchEnumerationType phoneNumber;
    @XmlElement(name = "Address", required = true)
    protected MatchEnumerationType address;
    @XmlElement(name = "CountrySubdivisionTaxId")
    protected MatchEnumerationType countrySubdivisionTaxId;
    @XmlElement(name = "NationalTaxId")
    protected MatchEnumerationType nationalTaxId;
    @XmlElement(name = "PrincipalMatch", required = true)
    protected List<PrincipalMatchType> principalMatch;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link MatchEnumerationType }
     *     
     */
    public MatchEnumerationType getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchEnumerationType }
     *     
     */
    public void setName(MatchEnumerationType value) {
        this.name = value;
    }

    /**
     * Gets the value of the doingBusinessAsName property.
     * 
     * @return
     *     possible object is
     *     {@link MatchEnumerationType }
     *     
     */
    public MatchEnumerationType getDoingBusinessAsName() {
        return doingBusinessAsName;
    }

    /**
     * Sets the value of the doingBusinessAsName property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchEnumerationType }
     *     
     */
    public void setDoingBusinessAsName(MatchEnumerationType value) {
        this.doingBusinessAsName = value;
    }

    /**
     * Gets the value of the phoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link MatchEnumerationType }
     *     
     */
    public MatchEnumerationType getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the value of the phoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchEnumerationType }
     *     
     */
    public void setPhoneNumber(MatchEnumerationType value) {
        this.phoneNumber = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link MatchEnumerationType }
     *     
     */
    public MatchEnumerationType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchEnumerationType }
     *     
     */
    public void setAddress(MatchEnumerationType value) {
        this.address = value;
    }

    /**
     * Gets the value of the countrySubdivisionTaxId property.
     * 
     * @return
     *     possible object is
     *     {@link MatchEnumerationType }
     *     
     */
    public MatchEnumerationType getCountrySubdivisionTaxId() {
        return countrySubdivisionTaxId;
    }

    /**
     * Sets the value of the countrySubdivisionTaxId property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchEnumerationType }
     *     
     */
    public void setCountrySubdivisionTaxId(MatchEnumerationType value) {
        this.countrySubdivisionTaxId = value;
    }

    /**
     * Gets the value of the nationalTaxId property.
     * 
     * @return
     *     possible object is
     *     {@link MatchEnumerationType }
     *     
     */
    public MatchEnumerationType getNationalTaxId() {
        return nationalTaxId;
    }

    /**
     * Sets the value of the nationalTaxId property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchEnumerationType }
     *     
     */
    public void setNationalTaxId(MatchEnumerationType value) {
        this.nationalTaxId = value;
    }

    /**
     * Gets the value of the principalMatch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the principalMatch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrincipalMatch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PrincipalMatchType }
     * 
     * 
     */
    public List<PrincipalMatchType> getPrincipalMatch() {
        if (principalMatch == null) {
            principalMatch = new ArrayList<PrincipalMatchType>();
        }
        return this.principalMatch;
    }

}
