//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.15 at 02:16:50 PM CDT 
//


package com.mastercard.api.moneysend.v2.mapping.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RequestId" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *         &lt;element name="SendingEligibility">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Eligible" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ReasonCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AccountNumber" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *                   &lt;element name="ICA" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="Currency">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="AlphaCurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="NumericCurrencyCode" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Country">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="AlphaCountryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="NumericCountryCode" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Brand">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="AcceptanceBrandCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ProductBrandCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ReceivingEligibility">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Eligible" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AccountNumber" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestId",
    "sendingEligibility",
    "receivingEligibility"
})
@XmlRootElement(name = "PanEligibility")
public class PanEligibility {

    @XmlElement(name = "RequestId")
    protected Integer requestId;
    @XmlElement(name = "SendingEligibility", required = true)
    protected SendingEligibility sendingEligibility;
    @XmlElement(name = "ReceivingEligibility", required = true)
    protected ReceivingEligibility receivingEligibility;

    /**
     * Gets the value of the requestId property.
     * 
     */
    public Integer getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the requestId property.
     * 
     */
    public void setRequestId(Integer value) {
        this.requestId = value;
    }

    /**
     * Gets the value of the sendingEligibility property.
     * 
     * @return
     *     possible object is
     *     {@link com.mastercard.api.moneysend.v2.mapping.domain.PanEligibility.SendingEligibility }
     *     
     */
    public SendingEligibility getSendingEligibility() {
        return sendingEligibility;
    }

    /**
     * Sets the value of the sendingEligibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.mastercard.api.moneysend.v2.mapping.domain.PanEligibility.SendingEligibility }
     *     
     */
    public void setSendingEligibility(SendingEligibility value) {
        this.sendingEligibility = value;
    }

    /**
     * Gets the value of the receivingEligibility property.
     * 
     * @return
     *     possible object is
     *     {@link com.mastercard.api.moneysend.v2.mapping.domain.PanEligibility.ReceivingEligibility }
     *     
     */
    public ReceivingEligibility getReceivingEligibility() {
        return receivingEligibility;
    }

    /**
     * Sets the value of the receivingEligibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.mastercard.api.moneysend.v2.mapping.domain.PanEligibility.ReceivingEligibility }
     *     
     */
    public void setReceivingEligibility(ReceivingEligibility value) {
        this.receivingEligibility = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Eligible" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AccountNumber" type="{http://www.w3.org/2001/XMLSchema}Long"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "eligible",
        "accountNumber"
    })
    public static class ReceivingEligibility {

        @XmlElement(name = "Eligible", required = true)
        protected Boolean eligible;
        @XmlElement(name = "AccountNumber")
        protected Long accountNumber;

        /**
         * Gets the value of the eligible property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public Boolean getEligible() {
            return eligible;
        }

        /**
         * Sets the value of the eligible property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEligible(Boolean value) {
            this.eligible = value;
        }

        /**
         * Gets the value of the accountNumber property.
         * 
         */
        public Long getAccountNumber() {
            return accountNumber;
        }

        /**
         * Sets the value of the accountNumber property.
         * 
         */
        public void setAccountNumber(Long value) {
            this.accountNumber = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Eligible" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ReasonCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AccountNumber" type="{http://www.w3.org/2001/XMLSchema}Long"/>
     *         &lt;element name="ICA" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="Currency">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="AlphaCurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="NumericCurrencyCode" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Country">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="AlphaCountryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="NumericCountryCode" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Brand">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="AcceptanceBrandCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ProductBrandCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "eligible",
        "reasonCode",
        "accountNumber",
        "ica",
        "currency",
        "country",
        "brand"
    })
    public static class SendingEligibility {

        @XmlElement(name = "Eligible", required = true)
        protected Boolean eligible;
        @XmlElement(name = "ReasonCode", required = true)
        protected String reasonCode;
        @XmlElement(name = "AccountNumber")
        protected Long accountNumber;
        @XmlElement(name = "ICA")
        protected Integer ica;
        @XmlElement(name = "Currency", required = true)
        protected Currency currency;
        @XmlElement(name = "Country", required = true)
        protected Country country;
        @XmlElement(name = "Brand", required = true)
        protected Brand brand;

        /**
         * Gets the value of the eligible property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public Boolean getEligible() {
            return eligible;
        }

        /**
         * Sets the value of the eligible property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEligible(Boolean value) {
            this.eligible = value;
        }

        /**
         * Gets the value of the reasonCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReasonCode() {
            return reasonCode;
        }

        /**
         * Sets the value of the reasonCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReasonCode(String value) {
            this.reasonCode = value;
        }

        /**
         * Gets the value of the accountNumber property.
         * 
         */
        public Long getAccountNumber() {
            return accountNumber;
        }

        /**
         * Sets the value of the accountNumber property.
         * 
         */
        public void setAccountNumber(Long value) {
            this.accountNumber = value;
        }

        /**
         * Gets the value of the ica property.
         * 
         */
        public Integer getICA() {
            return ica;
        }

        /**
         * Sets the value of the ica property.
         * 
         */
        public void setICA(Integer value) {
            this.ica = value;
        }

        /**
         * Gets the value of the currency property.
         * 
         * @return
         *     possible object is
         *     {@link com.mastercard.api.moneysend.v2.mapping.domain.PanEligibility.SendingEligibility.Currency }
         *     
         */
        public Currency getCurrency() {
            return currency;
        }

        /**
         * Sets the value of the currency property.
         * 
         * @param value
         *     allowed object is
         *     {@link com.mastercard.api.moneysend.v2.mapping.domain.PanEligibility.SendingEligibility.Currency }
         *     
         */
        public void setCurrency(Currency value) {
            this.currency = value;
        }

        /**
         * Gets the value of the country property.
         * 
         * @return
         *     possible object is
         *     {@link com.mastercard.api.moneysend.v2.mapping.domain.PanEligibility.SendingEligibility.Country }
         *     
         */
        public Country getCountry() {
            return country;
        }

        /**
         * Sets the value of the country property.
         * 
         * @param value
         *     allowed object is
         *     {@link com.mastercard.api.moneysend.v2.mapping.domain.PanEligibility.SendingEligibility.Country }
         *     
         */
        public void setCountry(Country value) {
            this.country = value;
        }

        /**
         * Gets the value of the brand property.
         * 
         * @return
         *     possible object is
         *     {@link com.mastercard.api.moneysend.v2.mapping.domain.PanEligibility.SendingEligibility.Brand }
         *     
         */
        public Brand getBrand() {
            return brand;
        }

        /**
         * Sets the value of the brand property.
         * 
         * @param value
         *     allowed object is
         *     {@link com.mastercard.api.moneysend.v2.mapping.domain.PanEligibility.SendingEligibility.Brand }
         *     
         */
        public void setBrand(Brand value) {
            this.brand = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="AcceptanceBrandCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ProductBrandCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "acceptanceBrandCode",
            "productBrandCode"
        })
        public static class Brand {

            @XmlElement(name = "AcceptanceBrandCode", required = true)
            protected String acceptanceBrandCode;
            @XmlElement(name = "ProductBrandCode", required = true)
            protected String productBrandCode;

            /**
             * Gets the value of the acceptanceBrandCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAcceptanceBrandCode() {
                return acceptanceBrandCode;
            }

            /**
             * Sets the value of the acceptanceBrandCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAcceptanceBrandCode(String value) {
                this.acceptanceBrandCode = value;
            }

            /**
             * Gets the value of the productBrandCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProductBrandCode() {
                return productBrandCode;
            }

            /**
             * Sets the value of the productBrandCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProductBrandCode(String value) {
                this.productBrandCode = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="AlphaCountryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="NumericCountryCode" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "alphaCountryCode",
            "numericCountryCode"
        })
        public static class Country {

            @XmlElement(name = "AlphaCountryCode", required = true)
            protected String alphaCountryCode;
            @XmlElement(name = "NumericCountryCode")
            protected Integer numericCountryCode;

            /**
             * Gets the value of the alphaCountryCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAlphaCountryCode() {
                return alphaCountryCode;
            }

            /**
             * Sets the value of the alphaCountryCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAlphaCountryCode(String value) {
                this.alphaCountryCode = value;
            }

            /**
             * Gets the value of the numericCountryCode property.
             * 
             */
            public Integer getNumericCountryCode() {
                return numericCountryCode;
            }

            /**
             * Sets the value of the numericCountryCode property.
             * 
             */
            public void setNumericCountryCode(Integer value) {
                this.numericCountryCode = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="AlphaCurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="NumericCurrencyCode" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "alphaCurrencyCode",
            "numericCurrencyCode"
        })
        public static class Currency {

            @XmlElement(name = "AlphaCurrencyCode", required = true)
            protected String alphaCurrencyCode;
            @XmlElement(name = "NumericCurrencyCode")
            protected Integer numericCurrencyCode;

            /**
             * Gets the value of the alphaCurrencyCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAlphaCurrencyCode() {
                return alphaCurrencyCode;
            }

            /**
             * Sets the value of the alphaCurrencyCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAlphaCurrencyCode(String value) {
                this.alphaCurrencyCode = value;
            }

            /**
             * Gets the value of the numericCurrencyCode property.
             * 
             */
            public Integer getNumericCurrencyCode() {
                return numericCurrencyCode;
            }

            /**
             * Sets the value of the numericCurrencyCode property.
             * 
             */
            public void setNumericCurrencyCode(Integer value) {
                this.numericCurrencyCode = value;
            }

        }

    }

}
