//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.28 at 08:41:56 PM CDT 
//


package com.mastercard.api.moneysend.v2.mapping.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LocalDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LocalTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TransactionReference" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *         &lt;element name="SenderName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SenderAddress">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Line1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Line2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CountrySubdivision" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="FundingCard">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AccountNumber" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *                   &lt;element name="ExpiryMonth" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="ExpiryYear" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="FundingMapped">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SubscriberId" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *                   &lt;element name="SubscriberType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SubscriberAlias" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="FundingUCAF" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FundingMasterCardAssignedId" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *         &lt;element name="FundingAmount">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ReceiverName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReceiverAddress">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Line1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Line2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CountrySubdivision" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ReceiverPhone" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *         &lt;element name="ReceivingCard">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AccountNumber" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ReceivingAmount">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Channel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UCAFSupport" type="{http://www.w3.org/2001/XMLSchema}Boolean"/>
 *         &lt;element name="ICA" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *         &lt;element name="ProcessorId" type="{http://www.w3.org/2001/XMLSchema}Long"/>
 *         &lt;element name="RoutingAndTransitNumber" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *         &lt;element name="CardAcceptor">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TransactionDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MerchantId" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "localDate",
    "localTime",
    "transactionReference",
    "senderName",
    "senderAddress",
    "fundingCard",
    "fundingMapped",
    "fundingUCAF",
    "fundingMasterCardAssignedId",
    "fundingAmount",
    "receiverName",
    "receiverAddress",
    "receiverPhone",
    "receivingCard",
    "receivingAmount",
    "channel",
    "ucafSupport",
    "ica",
    "processorId",
    "routingAndTransitNumber",
    "cardAcceptor",
    "transactionDesc",
    "merchantId"
})
@XmlRootElement(name = "TransferRequest")
public class TransferRequest {

    @XmlElement(name = "LocalDate")
    protected String localDate;
    @XmlElement(name = "LocalTime")
    protected String localTime;
    @XmlElement(name = "TransactionReference")
    protected Long transactionReference;
    @XmlElement(name = "SenderName", required = true)
    protected String senderName;
    @XmlElement(name = "SenderAddress", required = true)
    protected SenderAddress senderAddress;
    @XmlElement(name = "FundingCard", required = true)
    protected FundingCard fundingCard;
    @XmlElement(name = "FundingMapped", required = true)
    protected FundingMapped fundingMapped;
    @XmlElement(name = "FundingUCAF", required = true)
    protected String fundingUCAF;
    @XmlElement(name = "FundingMasterCardAssignedId")
    protected Integer fundingMasterCardAssignedId;
    @XmlElement(name = "FundingAmount", required = true)
    protected FundingAmount fundingAmount;
    @XmlElement(name = "ReceiverName", required = true)
    protected String receiverName;
    @XmlElement(name = "ReceiverAddress", required = true)
    protected ReceiverAddress receiverAddress;
    @XmlElement(name = "ReceiverPhone")
    protected Integer receiverPhone;
    @XmlElement(name = "ReceivingCard", required = true)
    protected ReceivingCard receivingCard;
    @XmlElement(name = "ReceivingAmount", required = true)
    protected ReceivingAmount receivingAmount;
    @XmlElement(name = "Channel", required = true)
    protected String channel;
    @XmlElement(name = "UCAFSupport", required = true)
    protected Boolean ucafSupport;
    @XmlElement(name = "ICA")
    protected String ica;
    @XmlElement(name = "ProcessorId")
    protected Long processorId;
    @XmlElement(name = "RoutingAndTransitNumber")
    protected Integer routingAndTransitNumber;
    @XmlElement(name = "CardAcceptor", required = true)
    protected CardAcceptor cardAcceptor;
    @XmlElement(name = "TransactionDesc", required = true)
    protected String transactionDesc;
    @XmlElement(name = "MerchantId")
    protected Integer merchantId;

    /**
     * Gets the value of the localDate property.
     * 
     */
    public String getLocalDate() {
        return localDate;
    }

    /**
     * Sets the value of the localDate property.
     * 
     */
    public void setLocalDate(String value) {
        this.localDate = value;
    }

    /**
     * Gets the value of the localTime property.
     * 
     */
    public String getLocalTime() {
        return localTime;
    }

    /**
     * Sets the value of the localTime property.
     * 
     */
    public void setLocalTime(String value) {
        this.localTime = value;
    }

    /**
     * Gets the value of the transactionReference property.
     * 
     */
    public Long getTransactionReference() {
        return transactionReference;
    }

    /**
     * Sets the value of the transactionReference property.
     * 
     */
    public void setTransactionReference(Long value) {
        this.transactionReference = value;
    }

    /**
     * Gets the value of the senderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderName() {
        return senderName;
    }

    /**
     * Sets the value of the senderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderName(String value) {
        this.senderName = value;
    }

    /**
     * Gets the value of the senderAddress property.
     * 
     * @return
     *     possible object is
     *     {@link com.mastercard.api.moneysend.v2.mapping.domain.TransferRequest.SenderAddress }
     *     
     */
    public SenderAddress getSenderAddress() {
        return senderAddress;
    }

    /**
     * Sets the value of the senderAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.mastercard.api.moneysend.v2.mapping.domain.TransferRequest.SenderAddress }
     *     
     */
    public void setSenderAddress(SenderAddress value) {
        this.senderAddress = value;
    }

    /**
     * Gets the value of the fundingCard property.
     * 
     * @return
     *     possible object is
     *     {@link com.mastercard.api.moneysend.v2.mapping.domain.TransferRequest.FundingCard }
     *     
     */
    public FundingCard getFundingCard() {
        return fundingCard;
    }

    /**
     * Sets the value of the fundingCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.mastercard.api.moneysend.v2.mapping.domain.TransferRequest.FundingCard }
     *     
     */
    public void setFundingCard(FundingCard value) {
        this.fundingCard = value;
    }

    /**
     * Gets the value of the fundingMapped property.
     * 
     * @return
     *     possible object is
     *     {@link com.mastercard.api.moneysend.v2.mapping.domain.TransferRequest.FundingMapped }
     *     
     */
    public FundingMapped getFundingMapped() {
        return fundingMapped;
    }

    /**
     * Sets the value of the fundingMapped property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.mastercard.api.moneysend.v2.mapping.domain.TransferRequest.FundingMapped }
     *     
     */
    public void setFundingMapped(FundingMapped value) {
        this.fundingMapped = value;
    }

    /**
     * Gets the value of the fundingUCAF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFundingUCAF() {
        return fundingUCAF;
    }

    /**
     * Sets the value of the fundingUCAF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFundingUCAF(String value) {
        this.fundingUCAF = value;
    }

    /**
     * Gets the value of the fundingMasterCardAssignedId property.
     * 
     */
    public Integer getFundingMasterCardAssignedId() {
        return fundingMasterCardAssignedId;
    }

    /**
     * Sets the value of the fundingMasterCardAssignedId property.
     * 
     */
    public void setFundingMasterCardAssignedId(Integer value) {
        this.fundingMasterCardAssignedId = value;
    }

    /**
     * Gets the value of the fundingAmount property.
     * 
     * @return
     *     possible object is
     *     {@link com.mastercard.api.moneysend.v2.mapping.domain.TransferRequest.FundingAmount }
     *     
     */
    public FundingAmount getFundingAmount() {
        return fundingAmount;
    }

    /**
     * Sets the value of the fundingAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.mastercard.api.moneysend.v2.mapping.domain.TransferRequest.FundingAmount }
     *     
     */
    public void setFundingAmount(FundingAmount value) {
        this.fundingAmount = value;
    }

    /**
     * Gets the value of the receiverName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * Sets the value of the receiverName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverName(String value) {
        this.receiverName = value;
    }

    /**
     * Gets the value of the receiverAddress property.
     * 
     * @return
     *     possible object is
     *     {@link com.mastercard.api.moneysend.v2.mapping.domain.TransferRequest.ReceiverAddress }
     *     
     */
    public ReceiverAddress getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * Sets the value of the receiverAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.mastercard.api.moneysend.v2.mapping.domain.TransferRequest.ReceiverAddress }
     *     
     */
    public void setReceiverAddress(ReceiverAddress value) {
        this.receiverAddress = value;
    }

    /**
     * Gets the value of the receiverPhone property.
     * 
     */
    public Integer getReceiverPhone() {
        return receiverPhone;
    }

    /**
     * Sets the value of the receiverPhone property.
     * 
     */
    public void setReceiverPhone(Integer value) {
        this.receiverPhone = value;
    }

    /**
     * Gets the value of the receivingCard property.
     * 
     * @return
     *     possible object is
     *     {@link com.mastercard.api.moneysend.v2.mapping.domain.TransferRequest.ReceivingCard }
     *     
     */
    public ReceivingCard getReceivingCard() {
        return receivingCard;
    }

    /**
     * Sets the value of the receivingCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.mastercard.api.moneysend.v2.mapping.domain.TransferRequest.ReceivingCard }
     *     
     */
    public void setReceivingCard(ReceivingCard value) {
        this.receivingCard = value;
    }

    /**
     * Gets the value of the receivingAmount property.
     * 
     * @return
     *     possible object is
     *     {@link com.mastercard.api.moneysend.v2.mapping.domain.TransferRequest.ReceivingAmount }
     *     
     */
    public ReceivingAmount getReceivingAmount() {
        return receivingAmount;
    }

    /**
     * Sets the value of the receivingAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.mastercard.api.moneysend.v2.mapping.domain.TransferRequest.ReceivingAmount }
     *     
     */
    public void setReceivingAmount(ReceivingAmount value) {
        this.receivingAmount = value;
    }

    /**
     * Gets the value of the channel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannel() {
        return channel;
    }

    /**
     * Sets the value of the channel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannel(String value) {
        this.channel = value;
    }

    /**
     * Gets the value of the ucafSupport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Boolean getUCAFSupport() {
        return ucafSupport;
    }

    /**
     * Sets the value of the ucafSupport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCAFSupport(Boolean value) {
        this.ucafSupport = value;
    }

    /**
     * Gets the value of the ica property.
     * 
     */
    public String getICA() {
        return ica;
    }

    /**
     * Sets the value of the ica property.
     * 
     */
    public void setICA(String value) {
        this.ica = value;
    }

    /**
     * Gets the value of the processorId property.
     * 
     */
    public Long getProcessorId() {
        return processorId;
    }

    /**
     * Sets the value of the processorId property.
     * 
     */
    public void setProcessorId(Long value) {
        this.processorId = value;
    }

    /**
     * Gets the value of the routingAndTransitNumber property.
     * 
     */
    public Integer getRoutingAndTransitNumber() {
        return routingAndTransitNumber;
    }

    /**
     * Sets the value of the routingAndTransitNumber property.
     * 
     */
    public void setRoutingAndTransitNumber(Integer value) {
        this.routingAndTransitNumber = value;
    }

    /**
     * Gets the value of the cardAcceptor property.
     * 
     * @return
     *     possible object is
     *     {@link com.mastercard.api.moneysend.v2.mapping.domain.TransferRequest.CardAcceptor }
     *     
     */
    public CardAcceptor getCardAcceptor() {
        return cardAcceptor;
    }

    /**
     * Sets the value of the cardAcceptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.mastercard.api.moneysend.v2.mapping.domain.TransferRequest.CardAcceptor }
     *     
     */
    public void setCardAcceptor(CardAcceptor value) {
        this.cardAcceptor = value;
    }

    /**
     * Gets the value of the transactionDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionDesc() {
        return transactionDesc;
    }

    /**
     * Sets the value of the transactionDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionDesc(String value) {
        this.transactionDesc = value;
    }

    /**
     * Gets the value of the merchantId property.
     * 
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * Sets the value of the merchantId property.
     * 
     */
    public void setMerchantId(Integer value) {
        this.merchantId = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "city",
        "state",
        "postalCode",
        "country"
    })
    public static class CardAcceptor {

        @XmlElement(name = "Name", required = true)
        protected String name;
        @XmlElement(name = "City", required = true)
        protected String city;
        @XmlElement(name = "State", required = true)
        protected String state;
        @XmlElement(name = "PostalCode")
        protected Integer postalCode;
        @XmlElement(name = "Country", required = true)
        protected String country;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the city property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCity() {
            return city;
        }

        /**
         * Sets the value of the city property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCity(String value) {
            this.city = value;
        }

        /**
         * Gets the value of the state property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getState() {
            return state;
        }

        /**
         * Sets the value of the state property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setState(String value) {
            this.state = value;
        }

        /**
         * Gets the value of the postalCode property.
         * 
         */
        public Integer getPostalCode() {
            return postalCode;
        }

        /**
         * Sets the value of the postalCode property.
         * 
         */
        public void setPostalCode(Integer value) {
            this.postalCode = value;
        }

        /**
         * Gets the value of the country property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountry() {
            return country;
        }

        /**
         * Sets the value of the country property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountry(String value) {
            this.country = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value",
        "currency"
    })
    public static class FundingAmount {

        @XmlElement(name = "Value")
        protected Integer value;
        @XmlElement(name = "Currency")
        protected Integer currency;

        /**
         * Gets the value of the value property.
         * 
         */
        public Integer getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(Integer value) {
            this.value = value;
        }

        /**
         * Gets the value of the currency property.
         * 
         */
        public Integer getCurrency() {
            return currency;
        }

        /**
         * Sets the value of the currency property.
         * 
         */
        public void setCurrency(Integer value) {
            this.currency = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AccountNumber" type="{http://www.w3.org/2001/XMLSchema}Long"/>
     *         &lt;element name="ExpiryMonth" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="ExpiryYear" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "accountNumber",
        "expiryMonth",
        "expiryYear"
    })
    public static class FundingCard {

        @XmlElement(name = "AccountNumber")
        protected Long accountNumber;
        @XmlElement(name = "ExpiryMonth")
        protected Integer expiryMonth;
        @XmlElement(name = "ExpiryYear")
        protected Integer expiryYear;

        /**
         * Gets the value of the accountNumber property.
         * 
         */
        public Long getAccountNumber() {
            return accountNumber;
        }

        /**
         * Sets the value of the accountNumber property.
         * 
         */
        public void setAccountNumber(Long value) {
            this.accountNumber = value;
        }

        /**
         * Gets the value of the expiryMonth property.
         * 
         */
        public Integer getExpiryMonth() {
            return expiryMonth;
        }

        /**
         * Sets the value of the expiryMonth property.
         * 
         */
        public void setExpiryMonth(Integer value) {
            this.expiryMonth = value;
        }

        /**
         * Gets the value of the expiryYear property.
         * 
         */
        public Integer getExpiryYear() {
            return expiryYear;
        }

        /**
         * Sets the value of the expiryYear property.
         * 
         */
        public void setExpiryYear(Integer value) {
            this.expiryYear = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SubscriberId" type="{http://www.w3.org/2001/XMLSchema}Long"/>
     *         &lt;element name="SubscriberType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SubscriberAlias" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "subscriberId",
        "subscriberType",
        "subscriberAlias"
    })
    public static class FundingMapped {

        @XmlElement(name = "SubscriberId")
        protected String subscriberId;
        @XmlElement(name = "SubscriberType", required = true)
        protected String subscriberType;
        @XmlElement(name = "SubscriberAlias", required = true)
        protected String subscriberAlias;

        /**
         * Gets the value of the subscriberId property.
         * 
         */
        public String getSubscriberId() {
            return subscriberId;
        }

        /**
         * Sets the value of the subscriberId property.
         * 
         */
        public void setSubscriberId(String value) {
            this.subscriberId = value;
        }

        /**
         * Gets the value of the subscriberType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubscriberType() {
            return subscriberType;
        }

        /**
         * Sets the value of the subscriberType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubscriberType(String value) {
            this.subscriberType = value;
        }

        /**
         * Gets the value of the subscriberAlias property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubscriberAlias() {
            return subscriberAlias;
        }

        /**
         * Sets the value of the subscriberAlias property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubscriberAlias(String value) {
            this.subscriberAlias = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Line1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Line2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CountrySubdivision" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "line1",
        "line2",
        "city",
        "countrySubdivision",
        "postalCode",
        "country"
    })
    public static class ReceiverAddress {

        @XmlElement(name = "Line1", required = true)
        protected String line1;
        @XmlElement(name = "Line2", required = true)
        protected String line2;
        @XmlElement(name = "City", required = true)
        protected String city;
        @XmlElement(name = "CountrySubdivision", required = true)
        protected String countrySubdivision;
        @XmlElement(name = "PostalCode")
        protected Integer postalCode;
        @XmlElement(name = "Country", required = true)
        protected String country;

        /**
         * Gets the value of the line1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLine1() {
            return line1;
        }

        /**
         * Sets the value of the line1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLine1(String value) {
            this.line1 = value;
        }

        /**
         * Gets the value of the line2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLine2() {
            return line2;
        }

        /**
         * Sets the value of the line2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLine2(String value) {
            this.line2 = value;
        }

        /**
         * Gets the value of the city property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCity() {
            return city;
        }

        /**
         * Sets the value of the city property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCity(String value) {
            this.city = value;
        }

        /**
         * Gets the value of the countrySubdivision property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountrySubdivision() {
            return countrySubdivision;
        }

        /**
         * Sets the value of the countrySubdivision property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountrySubdivision(String value) {
            this.countrySubdivision = value;
        }

        /**
         * Gets the value of the postalCode property.
         * 
         */
        public Integer getPostalCode() {
            return postalCode;
        }

        /**
         * Sets the value of the postalCode property.
         * 
         */
        public void setPostalCode(Integer value) {
            this.postalCode = value;
        }

        /**
         * Gets the value of the country property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountry() {
            return country;
        }

        /**
         * Sets the value of the country property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountry(String value) {
            this.country = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value",
        "currency"
    })
    public static class ReceivingAmount {

        @XmlElement(name = "Value")
        protected Integer value;
        @XmlElement(name = "Currency")
        protected Integer currency;

        /**
         * Gets the value of the value property.
         * 
         */
        public Integer getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(Integer value) {
            this.value = value;
        }

        /**
         * Gets the value of the currency property.
         * 
         */
        public Integer getCurrency() {
            return currency;
        }

        /**
         * Sets the value of the currency property.
         * 
         */
        public void setCurrency(Integer value) {
            this.currency = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AccountNumber" type="{http://www.w3.org/2001/XMLSchema}Long"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "accountNumber"
    })
    public static class ReceivingCard {

        @XmlElement(name = "AccountNumber")
        protected Long accountNumber;

        /**
         * Gets the value of the accountNumber property.
         * 
         */
        public Long getAccountNumber() {
            return accountNumber;
        }

        /**
         * Sets the value of the accountNumber property.
         * 
         */
        public void setAccountNumber(Long value) {
            this.accountNumber = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Line1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Line2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CountrySubdivision" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "line1",
        "line2",
        "city",
        "countrySubdivision",
        "postalCode",
        "country"
    })
    public static class SenderAddress {

        @XmlElement(name = "Line1", required = true)
        protected String line1;
        @XmlElement(name = "Line2", required = true)
        protected String line2;
        @XmlElement(name = "City", required = true)
        protected String city;
        @XmlElement(name = "CountrySubdivision", required = true)
        protected String countrySubdivision;
        @XmlElement(name = "PostalCode")
        protected Integer postalCode;
        @XmlElement(name = "Country", required = true)
        protected String country;

        /**
         * Gets the value of the line1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLine1() {
            return line1;
        }

        /**
         * Sets the value of the line1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLine1(String value) {
            this.line1 = value;
        }

        /**
         * Gets the value of the line2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLine2() {
            return line2;
        }

        /**
         * Sets the value of the line2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLine2(String value) {
            this.line2 = value;
        }

        /**
         * Gets the value of the city property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCity() {
            return city;
        }

        /**
         * Sets the value of the city property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCity(String value) {
            this.city = value;
        }

        /**
         * Gets the value of the countrySubdivision property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountrySubdivision() {
            return countrySubdivision;
        }

        /**
         * Sets the value of the countrySubdivision property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountrySubdivision(String value) {
            this.countrySubdivision = value;
        }

        /**
         * Gets the value of the postalCode property.
         * 
         */
        public Integer getPostalCode() {
            return postalCode;
        }

        /**
         * Sets the value of the postalCode property.
         * 
         */
        public void setPostalCode(Integer value) {
            this.postalCode = value;
        }

        /**
         * Gets the value of the country property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountry() {
            return country;
        }

        /**
         * Sets the value of the country property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountry(String value) {
            this.country = value;
        }

    }

}
