//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.13 at 03:17:08 PM CST 
//


package com.mastercard.api.location.v1.atms.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PageOffset" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="TotalCount" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="Atm">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Location">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Distance" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="DistanceUnit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Address">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Line1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Line2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="CountrySubdivision">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="Country">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Point">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Latitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="Longitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="LocationType">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="HandicapAccessible" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Camera" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Availability" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AccessFees" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Owner" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SharedDeposit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SurchargeFreeAlliance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SurchargeFreeAllianceNetwork" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Sponsor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SupportEMV" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pageOffset",
    "totalCount",
    "atm"
})
@XmlRootElement(name = "Atms")
public class Atms {

    @XmlElement(name = "PageOffset")
    protected byte pageOffset;
    @XmlElement(name = "TotalCount")
    protected short totalCount;
    @XmlElement(name = "Atm", required = true)
    protected List<Atm> atm;

    /**
     * Gets the value of the pageOffset property.
     * 
     */
    public byte getPageOffset() {
        return pageOffset;
    }

    /**
     * Sets the value of the pageOffset property.
     * 
     */
    public void setPageOffset(byte value) {
        this.pageOffset = value;
    }

    /**
     * Gets the value of the totalCount property.
     * 
     */
    public short getTotalCount() {
        return totalCount;
    }

    /**
     * Sets the value of the totalCount property.
     * 
     */
    public void setTotalCount(short value) {
        this.totalCount = value;
    }

    /**
     * Gets the value of the atm property.
     * 
     * @return
     *     possible object is
     *     {@link com.mastercard.api.location.v1.atms.domain.Atms.Atm }
     *     
     */
    public List<Atm> getAtm() {
        return atm;
    }

    /**
     * Sets the value of the atm property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.mastercard.api.location.v1.atms.domain.Atms.Atm }
     *     
     */
    public void setAtm(List<Atm> value) {
        this.atm = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Location">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Distance" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="DistanceUnit" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Address">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Line1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Line2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="CountrySubdivision">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="Country">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Point">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Latitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                             &lt;element name="Longitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="LocationType">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="HandicapAccessible" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Camera" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Availability" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AccessFees" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Owner" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SharedDeposit" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SurchargeFreeAlliance" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SurchargeFreeAllianceNetwork" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Sponsor" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SupportEMV" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "location",
        "handicapAccessible",
        "camera",
        "availability",
        "accessFees",
        "owner",
        "sharedDeposit",
        "surchargeFreeAlliance",
        "surchargeFreeAllianceNetwork",
        "sponsor",
        "supportEMV"
    })
    public static class Atm {

        @XmlElement(name = "Location", required = true)
        protected Location location;
        @XmlElement(name = "HandicapAccessible", required = true)
        protected String handicapAccessible;
        @XmlElement(name = "Camera", required = true)
        protected String camera;
        @XmlElement(name = "Availability", required = true)
        protected String availability;
        @XmlElement(name = "AccessFees", required = true)
        protected String accessFees;
        @XmlElement(name = "Owner", required = true)
        protected String owner;
        @XmlElement(name = "SharedDeposit", required = true)
        protected String sharedDeposit;
        @XmlElement(name = "SurchargeFreeAlliance", required = true)
        protected String surchargeFreeAlliance;
        @XmlElement(name = "SurchargeFreeAllianceNetwork", required = true)
        protected String surchargeFreeAllianceNetwork;
        @XmlElement(name = "Sponsor", required = true)
        protected String sponsor;
        @XmlElement(name = "SupportEMV")
        protected byte supportEMV;

        /**
         * Gets the value of the location property.
         * 
         * @return
         *     possible object is
         *     {@link com.mastercard.api.location.v1.atms.domain.Atms.Atm.Location }
         *     
         */
        public Location getLocation() {
            return location;
        }

        /**
         * Sets the value of the location property.
         * 
         * @param value
         *     allowed object is
         *     {@link com.mastercard.api.location.v1.atms.domain.Atms.Atm.Location }
         *     
         */
        public void setLocation(Location value) {
            this.location = value;
        }

        /**
         * Gets the value of the handicapAccessible property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHandicapAccessible() {
            return handicapAccessible;
        }

        /**
         * Sets the value of the handicapAccessible property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHandicapAccessible(String value) {
            this.handicapAccessible = value;
        }

        /**
         * Gets the value of the camera property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCamera() {
            return camera;
        }

        /**
         * Sets the value of the camera property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCamera(String value) {
            this.camera = value;
        }

        /**
         * Gets the value of the availability property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAvailability() {
            return availability;
        }

        /**
         * Sets the value of the availability property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAvailability(String value) {
            this.availability = value;
        }

        /**
         * Gets the value of the accessFees property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccessFees() {
            return accessFees;
        }

        /**
         * Sets the value of the accessFees property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccessFees(String value) {
            this.accessFees = value;
        }

        /**
         * Gets the value of the owner property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOwner() {
            return owner;
        }

        /**
         * Sets the value of the owner property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOwner(String value) {
            this.owner = value;
        }

        /**
         * Gets the value of the sharedDeposit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSharedDeposit() {
            return sharedDeposit;
        }

        /**
         * Sets the value of the sharedDeposit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSharedDeposit(String value) {
            this.sharedDeposit = value;
        }

        /**
         * Gets the value of the surchargeFreeAlliance property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSurchargeFreeAlliance() {
            return surchargeFreeAlliance;
        }

        /**
         * Sets the value of the surchargeFreeAlliance property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSurchargeFreeAlliance(String value) {
            this.surchargeFreeAlliance = value;
        }

        /**
         * Gets the value of the surchargeFreeAllianceNetwork property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSurchargeFreeAllianceNetwork() {
            return surchargeFreeAllianceNetwork;
        }

        /**
         * Sets the value of the surchargeFreeAllianceNetwork property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSurchargeFreeAllianceNetwork(String value) {
            this.surchargeFreeAllianceNetwork = value;
        }

        /**
         * Gets the value of the sponsor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSponsor() {
            return sponsor;
        }

        /**
         * Sets the value of the sponsor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSponsor(String value) {
            this.sponsor = value;
        }

        /**
         * Gets the value of the supportEMV property.
         * 
         */
        public byte getSupportEMV() {
            return supportEMV;
        }

        /**
         * Sets the value of the supportEMV property.
         * 
         */
        public void setSupportEMV(byte value) {
            this.supportEMV = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Distance" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="DistanceUnit" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Address">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Line1" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Line2" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="CountrySubdivision">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="Country">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Point">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Latitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                   &lt;element name="Longitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="LocationType">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "distance",
            "distanceUnit",
            "address",
            "point",
            "locationType"
        })
        public static class Location {

            @XmlElement(name = "Name", required = true)
            protected String name;
            @XmlElement(name = "Distance")
            protected float distance;
            @XmlElement(name = "DistanceUnit", required = true)
            protected String distanceUnit;
            @XmlElement(name = "Address", required = true)
            protected Address address;
            @XmlElement(name = "Point", required = true)
            protected Point point;
            @XmlElement(name = "LocationType", required = true)
            protected LocationType locationType;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the distance property.
             * 
             */
            public float getDistance() {
                return distance;
            }

            /**
             * Sets the value of the distance property.
             * 
             */
            public void setDistance(float value) {
                this.distance = value;
            }

            /**
             * Gets the value of the distanceUnit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDistanceUnit() {
                return distanceUnit;
            }

            /**
             * Sets the value of the distanceUnit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDistanceUnit(String value) {
                this.distanceUnit = value;
            }

            /**
             * Gets the value of the address property.
             * 
             * @return
             *     possible object is
             *     {@link com.mastercard.api.location.v1.atms.domain.Atms.Atm.Location.Address }
             *     
             */
            public Address getAddress() {
                return address;
            }

            /**
             * Sets the value of the address property.
             * 
             * @param value
             *     allowed object is
             *     {@link com.mastercard.api.location.v1.atms.domain.Atms.Atm.Location.Address }
             *     
             */
            public void setAddress(Address value) {
                this.address = value;
            }

            /**
             * Gets the value of the point property.
             * 
             * @return
             *     possible object is
             *     {@link com.mastercard.api.location.v1.atms.domain.Atms.Atm.Location.Point }
             *     
             */
            public Point getPoint() {
                return point;
            }

            /**
             * Sets the value of the point property.
             * 
             * @param value
             *     allowed object is
             *     {@link com.mastercard.api.location.v1.atms.domain.Atms.Atm.Location.Point }
             *     
             */
            public void setPoint(Point value) {
                this.point = value;
            }

            /**
             * Gets the value of the locationType property.
             * 
             * @return
             *     possible object is
             *     {@link com.mastercard.api.location.v1.atms.domain.Atms.Atm.Location.LocationType }
             *     
             */
            public LocationType getLocationType() {
                return locationType;
            }

            /**
             * Sets the value of the locationType property.
             * 
             * @param value
             *     allowed object is
             *     {@link com.mastercard.api.location.v1.atms.domain.Atms.Atm.Location.LocationType }
             *     
             */
            public void setLocationType(LocationType value) {
                this.locationType = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Line1" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Line2" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="CountrySubdivision">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="Country">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "line1",
                "line2",
                "city",
                "postalCode",
                "countrySubdivision",
                "country"
            })
            public static class Address {

                @XmlElement(name = "Line1", required = true)
                protected String line1;
                @XmlElement(name = "Line2", required = true)
                protected String line2;
                @XmlElement(name = "City", required = true)
                protected String city;
                @XmlElement(name = "PostalCode")
                protected int postalCode;
                @XmlElement(name = "CountrySubdivision", required = true)
                protected CountrySubdivision countrySubdivision;
                @XmlElement(name = "Country", required = true)
                protected Country country;

                /**
                 * Gets the value of the line1 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLine1() {
                    return line1;
                }

                /**
                 * Sets the value of the line1 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLine1(String value) {
                    this.line1 = value;
                }

                /**
                 * Gets the value of the line2 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLine2() {
                    return line2;
                }

                /**
                 * Sets the value of the line2 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLine2(String value) {
                    this.line2 = value;
                }

                /**
                 * Gets the value of the city property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCity() {
                    return city;
                }

                /**
                 * Sets the value of the city property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCity(String value) {
                    this.city = value;
                }

                /**
                 * Gets the value of the postalCode property.
                 * 
                 */
                public int getPostalCode() {
                    return postalCode;
                }

                /**
                 * Sets the value of the postalCode property.
                 * 
                 */
                public void setPostalCode(int value) {
                    this.postalCode = value;
                }

                /**
                 * Gets the value of the countrySubdivision property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link com.mastercard.api.location.v1.atms.domain.Atms.Atm.Location.Address.CountrySubdivision }
                 *     
                 */
                public CountrySubdivision getCountrySubdivision() {
                    return countrySubdivision;
                }

                /**
                 * Sets the value of the countrySubdivision property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link com.mastercard.api.location.v1.atms.domain.Atms.Atm.Location.Address.CountrySubdivision }
                 *     
                 */
                public void setCountrySubdivision(CountrySubdivision value) {
                    this.countrySubdivision = value;
                }

                /**
                 * Gets the value of the country property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link com.mastercard.api.location.v1.atms.domain.Atms.Atm.Location.Address.Country }
                 *     
                 */
                public Country getCountry() {
                    return country;
                }

                /**
                 * Sets the value of the country property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link com.mastercard.api.location.v1.atms.domain.Atms.Atm.Location.Address.Country }
                 *     
                 */
                public void setCountry(Country value) {
                    this.country = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "name",
                    "code"
                })
                public static class Country {

                    @XmlElement(name = "Name", required = true)
                    protected String name;
                    @XmlElement(name = "Code", required = true)
                    protected String code;

                    /**
                     * Gets the value of the name property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getName() {
                        return name;
                    }

                    /**
                     * Sets the value of the name property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setName(String value) {
                        this.name = value;
                    }

                    /**
                     * Gets the value of the code property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getCode() {
                        return code;
                    }

                    /**
                     * Sets the value of the code property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setCode(String value) {
                        this.code = value;
                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "name",
                    "code"
                })
                public static class CountrySubdivision {

                    @XmlElement(name = "Name", required = true)
                    protected String name;
                    @XmlElement(name = "Code", required = true)
                    protected String code;

                    /**
                     * Gets the value of the name property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getName() {
                        return name;
                    }

                    /**
                     * Sets the value of the name property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setName(String value) {
                        this.name = value;
                    }

                    /**
                     * Gets the value of the code property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getCode() {
                        return code;
                    }

                    /**
                     * Sets the value of the code property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setCode(String value) {
                        this.code = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "type"
            })
            public static class LocationType {

                @XmlElement(name = "Type", required = true)
                protected String type;

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Latitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *         &lt;element name="Longitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "latitude",
                "longitude"
            })
            public static class Point {

                @XmlElement(name = "Latitude")
                protected float latitude;
                @XmlElement(name = "Longitude")
                protected float longitude;

                /**
                 * Gets the value of the latitude property.
                 * 
                 */
                public float getLatitude() {
                    return latitude;
                }

                /**
                 * Sets the value of the latitude property.
                 * 
                 */
                public void setLatitude(float value) {
                    this.latitude = value;
                }

                /**
                 * Gets the value of the longitude property.
                 * 
                 */
                public float getLongitude() {
                    return longitude;
                }

                /**
                 * Sets the value of the longitude property.
                 * 
                 */
                public void setLongitude(float value) {
                    this.longitude = value;
                }

            }

        }

    }

}
