//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.20 at 01:33:12 PM CDT 
//


package com.mastercard.api.mdes.csrapi.v1.token.provision.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Used solely in conjunction with the "swap" action type.
 */

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CurrentPan" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="SecureElementId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TokenUniqueId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Action" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReasonCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AuditInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="UserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Organization" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="NewPan">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="ExpiryDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CardSequenceNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="UpdateWalletServiceProvider" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "currentPan",
    "secureElementId",
    "tokenUniqueId",
    "action",
    "comments",
    "reasonCode",
    "auditInfo",
    "newPan"
})
@XmlRootElement(name = "ProvisioningRequest")
public class SwapProvisioningRequest implements ProvisioningDomainMarker {

    @XmlElement(name = "CurrentPan")
    protected long currentPan;
    @XmlElement(name = "SecureElementId", required = true)
    protected String secureElementId;
    @XmlElement(name = "TokenUniqueId", required = true)
    protected String tokenUniqueId;
    @XmlElement(name = "Action", required = true)
    protected String action;
    @XmlElement(name = "Comments", required = true)
    protected String comments;
    @XmlElement(name = "ReasonCode", required = true)
    protected String reasonCode;
    @XmlElement(name = "AuditInfo", required = true)
    protected AuditInfo auditInfo;
    @XmlElement(name = "NewPan", required = true)
    protected NewPan newPan;

    /**
     * Gets the value of the currentPan property.
     * 
     */
    public long getCurrentPan() {
        return currentPan;
    }

    /**
     * Sets the value of the currentPan property.
     * 
     */
    public void setCurrentPan(long value) {
        this.currentPan = value;
    }

    /**
     * Gets the value of the secureElementId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecureElementId() {
        return secureElementId;
    }

    /**
     * Sets the value of the secureElementId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecureElementId(String value) {
        this.secureElementId = value;
    }

    /**
     * Gets the value of the tokenUniqueId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenUniqueId() {
        return tokenUniqueId;
    }

    /**
     * Sets the value of the tokenUniqueId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenUniqueId(String value) {
        this.tokenUniqueId = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the reasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonCode() {
        return reasonCode;
    }

    /**
     * Sets the value of the reasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonCode(String value) {
        this.reasonCode = value;
    }

    /**
     * Gets the value of the auditInfo property.
     * 
     * @return
     *     possible object is
     *     {@link com.mastercard.api.mdes.csrapi.v1.token.provision.domain.SwapProvisioningRequest.AuditInfo }
     *     
     */
    public AuditInfo getAuditInfo() {
        return auditInfo;
    }

    /**
     * Sets the value of the auditInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.mastercard.api.mdes.csrapi.v1.token.provision.domain.SwapProvisioningRequest.AuditInfo }
     *     
     */
    public void setAuditInfo(AuditInfo value) {
        this.auditInfo = value;
    }

    /**
     * Gets the value of the newPan property.
     * 
     * @return
     *     possible object is
     *     {@link com.mastercard.api.mdes.csrapi.v1.token.provision.domain.SwapProvisioningRequest.NewPan }
     *     
     */
    public NewPan getNewPan() {
        return newPan;
    }

    /**
     * Sets the value of the newPan property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.mastercard.api.mdes.csrapi.v1.token.provision.domain.SwapProvisioningRequest.NewPan }
     *     
     */
    public void setNewPan(NewPan value) {
        this.newPan = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="UserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Organization" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userId",
        "userName",
        "organization"
    })
    public static class AuditInfo {

        @XmlElement(name = "UserId", required = true)
        protected String userId;
        @XmlElement(name = "UserName", required = true)
        protected String userName;
        @XmlElement(name = "Organization", required = true)
        protected String organization;

        /**
         * Gets the value of the userId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserId() {
            return userId;
        }

        /**
         * Sets the value of the userId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserId(String value) {
            this.userId = value;
        }

        /**
         * Gets the value of the userName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserName() {
            return userName;
        }

        /**
         * Sets the value of the userName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserName(String value) {
            this.userName = value;
        }

        /**
         * Gets the value of the organization property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrganization() {
            return organization;
        }

        /**
         * Sets the value of the organization property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrganization(String value) {
            this.organization = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="ExpiryDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CardSequenceNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="UpdateWalletServiceProvider" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "expiryDate",
        "cardSequenceNumber",
        "updateWalletServiceProvider"
    })
    public static class NewPan {

        @XmlElement(name = "Id")
        protected Long id;
        @XmlElement(name = "ExpiryDate", required = true)
        protected String expiryDate;
        @XmlElement(name = "CardSequenceNumber", required = true)
        protected String cardSequenceNumber;
        @XmlElement(name = "UpdateWalletServiceProvider")
        protected Long updateWalletServiceProvider;

        /**
         * Gets the value of the id property.
         * 
         */
        public Long getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(long value) {
            this.id = value;
        }

        /**
         * Gets the value of the expiryDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExpiryDate() {
            return expiryDate;
        }

        /**
         * Sets the value of the expiryDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExpiryDate(String value) {
            this.expiryDate = value;
        }

        /**
         * Gets the value of the cardSequenceNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCardSequenceNumber() {
            return cardSequenceNumber;
        }

        /**
         * Sets the value of the cardSequenceNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCardSequenceNumber(String value) {
            this.cardSequenceNumber = value;
        }

        /**
         * Gets the value of the updateWalletServiceProvider property.
         * 
         */
        public Long getUpdateWalletServiceProvider() {
            return updateWalletServiceProvider;
        }

        /**
         * Sets the value of the updateWalletServiceProvider property.
         * 
         */
        public void setUpdateWalletServiceProvider(Long value) {
            this.updateWalletServiceProvider = value;
        }

    }

}
