//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.13 at 03:28:15 PM CDT 
//


package com.mastercard.api.mdes.csrapi.v1.systemstatus.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SystemResponse">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ContentId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="ContentHeader" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ContentText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ContentStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="LastModifiedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "systemResponse"
})
@XmlRootElement(name = "systemStatusResponses")
public class SystemStatusResponses {

    @XmlElement(name = "SystemResponse", required = true)
    protected SystemResponse systemResponse;

    /**
     * Gets the value of the systemResponse property.
     * 
     * @return
     *     possible object is
     *     {@link com.mastercard.api.mdes.csrapi.v1.systemstatus.domain.SystemStatusResponses.SystemResponse }
     *     
     */
    public SystemResponse getSystemResponse() {
        return systemResponse;
    }

    /**
     * Sets the value of the systemResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.mastercard.api.mdes.csrapi.v1.systemstatus.domain.SystemStatusResponses.SystemResponse }
     *     
     */
    public void setSystemResponse(SystemResponse value) {
        this.systemResponse = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ContentId" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="ContentHeader" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ContentText" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ContentStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="LastModifiedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "contentId",
        "contentHeader",
        "contentText",
        "contentStatus",
        "userId",
        "lastModifiedDate"
    })
    public static class SystemResponse {

        @XmlElement(name = "ContentId")
        protected int contentId;
        @XmlElement(name = "ContentHeader", required = true)
        protected String contentHeader;
        @XmlElement(name = "ContentText", required = true)
        protected String contentText;
        @XmlElement(name = "ContentStatus", required = true)
        protected String contentStatus;
        @XmlElement(name = "UserId")
        protected int userId;
        @XmlElement(name = "LastModifiedDate", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar lastModifiedDate;

        /**
         * Gets the value of the contentId property.
         * 
         */
        public int getContentId() {
            return contentId;
        }

        /**
         * Sets the value of the contentId property.
         * 
         */
        public void setContentId(int value) {
            this.contentId = value;
        }

        /**
         * Gets the value of the contentHeader property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContentHeader() {
            return contentHeader;
        }

        /**
         * Sets the value of the contentHeader property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContentHeader(String value) {
            this.contentHeader = value;
        }

        /**
         * Gets the value of the contentText property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContentText() {
            return contentText;
        }

        /**
         * Sets the value of the contentText property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContentText(String value) {
            this.contentText = value;
        }

        /**
         * Gets the value of the contentStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContentStatus() {
            return contentStatus;
        }

        /**
         * Sets the value of the contentStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContentStatus(String value) {
            this.contentStatus = value;
        }

        /**
         * Gets the value of the userId property.
         * 
         */
        public int getUserId() {
            return userId;
        }

        /**
         * Sets the value of the userId property.
         * 
         */
        public void setUserId(int value) {
            this.userId = value;
        }

        /**
         * Gets the value of the lastModifiedDate property.
         * 
         * @return
         *     possible object is
         *     {@link javax.xml.datatype.XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getLastModifiedDate() {
            return lastModifiedDate;
        }

        /**
         * Sets the value of the lastModifiedDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link javax.xml.datatype.XMLGregorianCalendar }
         *     
         */
        public void setLastModifiedDate(XMLGregorianCalendar value) {
            this.lastModifiedDate = value;
        }

    }

}
