//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.16 at 10:31:21 AM CDT 
//


package com.mastercard.api.merchantid.v1.merchantid.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReturnedMerchants">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Merchant">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Address">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Line1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Line2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                                       &lt;element name="CountrySubdivision">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="Country">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="PhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="BrandName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="MerchantCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="MerchantDbaName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="DescriptorText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="LegalCorporateName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="BrickCount" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                             &lt;element name="Comment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="LocationId" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                             &lt;element name="OnlineCount" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                             &lt;element name="OtherCount" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                             &lt;element name="SoleProprietorName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "message",
    "returnedMerchants"
})
@XmlRootElement(name = "MerchantIds")
public class MerchantIds {

    @XmlElement(name = "Message", required = true)
    protected String message;
    @XmlElement(name = "ReturnedMerchants", required = true)
    protected ReturnedMerchants returnedMerchants;

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the returnedMerchants property.
     * 
     * @return
     *     possible object is
     *     {@link com.mastercard.api.merchantid.v1.merchantid.domain.MerchantIds.ReturnedMerchants }
     *     
     */
    public ReturnedMerchants getReturnedMerchants() {
        return returnedMerchants;
    }

    /**
     * Sets the value of the returnedMerchants property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.mastercard.api.merchantid.v1.merchantid.domain.MerchantIds.ReturnedMerchants }
     *     
     */
    public void setReturnedMerchants(ReturnedMerchants value) {
        this.returnedMerchants = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Merchant">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Address">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Line1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Line2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *                             &lt;element name="CountrySubdivision">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="Country">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="PhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="BrandName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="MerchantCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="MerchantDbaName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="DescriptorText" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="LegalCorporateName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="BrickCount" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *                   &lt;element name="Comment" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="LocationId" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *                   &lt;element name="OnlineCount" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *                   &lt;element name="OtherCount" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *                   &lt;element name="SoleProprietorName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "merchant"
    })
    public static class ReturnedMerchants {

        @XmlElement(name = "Merchant", required = true)
        protected List<Merchant> merchant;

        /**
         * Gets the value of the merchant property.
         * 
         * @return
         *     possible object is
         *     {@link com.mastercard.api.merchantid.v1.merchantid.domain.MerchantIds.ReturnedMerchants.Merchant }
         *     
         */
        public List<Merchant> getMerchant() {
            return merchant;
        }

        /**
         * Sets the value of the merchant property.
         * 
         * @param value
         *     allowed object is
         *     {@link com.mastercard.api.merchantid.v1.merchantid.domain.MerchantIds.ReturnedMerchants.Merchant }
         *     
         */
        public void setMerchant(List<Merchant> value) {
            this.merchant = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Address">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Line1" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Line2" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
         *                   &lt;element name="CountrySubdivision">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="Country">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="PhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="BrandName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="MerchantCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="MerchantDbaName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="DescriptorText" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="LegalCorporateName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="BrickCount" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
         *         &lt;element name="Comment" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="LocationId" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
         *         &lt;element name="OnlineCount" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
         *         &lt;element name="OtherCount" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
         *         &lt;element name="SoleProprietorName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "address",
            "phoneNumber",
            "brandName",
            "merchantCategory",
            "merchantDbaName",
            "descriptorText",
            "legalCorporateName",
            "brickCount",
            "comment",
            "locationId",
            "onlineCount",
            "otherCount",
            "soleProprietorName"
        })
        public static class Merchant {

            @XmlElement(name = "Address", required = true)
            protected Address address;
            @XmlElement(name = "PhoneNumber", required = true)
            protected String phoneNumber;
            @XmlElement(name = "BrandName", required = true)
            protected String brandName;
            @XmlElement(name = "MerchantCategory", required = true)
            protected String merchantCategory;
            @XmlElement(name = "MerchantDbaName", required = true)
            protected String merchantDbaName;
            @XmlElement(name = "DescriptorText", required = true)
            protected String descriptorText;
            @XmlElement(name = "LegalCorporateName", required = true)
            protected String legalCorporateName;
            @XmlElement(name = "BrickCount")
            protected Integer brickCount;
            @XmlElement(name = "Comment", required = true)
            protected String comment;
            @XmlElement(name = "LocationId")
            protected Integer locationId;
            @XmlElement(name = "OnlineCount")
            protected Integer onlineCount;
            @XmlElement(name = "OtherCount")
            protected Integer otherCount;
            @XmlElement(name = "SoleProprietorName", required = true)
            protected String soleProprietorName;

            /**
             * Gets the value of the address property.
             * 
             * @return
             *     possible object is
             *     {@link com.mastercard.api.merchantid.v1.merchantid.domain.MerchantIds.ReturnedMerchants.Merchant.Address }
             *     
             */
            public Address getAddress() {
                return address;
            }

            /**
             * Sets the value of the address property.
             * 
             * @param value
             *     allowed object is
             *     {@link com.mastercard.api.merchantid.v1.merchantid.domain.MerchantIds.ReturnedMerchants.Merchant.Address }
             *     
             */
            public void setAddress(Address value) {
                this.address = value;
            }

            /**
             * Gets the value of the phoneNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPhoneNumber() {
                return phoneNumber;
            }

            /**
             * Sets the value of the phoneNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPhoneNumber(String value) {
                this.phoneNumber = value;
            }

            /**
             * Gets the value of the brandName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBrandName() {
                return brandName;
            }

            /**
             * Sets the value of the brandName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBrandName(String value) {
                this.brandName = value;
            }

            /**
             * Gets the value of the merchantCategory property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMerchantCategory() {
                return merchantCategory;
            }

            /**
             * Sets the value of the merchantCategory property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMerchantCategory(String value) {
                this.merchantCategory = value;
            }

            /**
             * Gets the value of the merchantDbaName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMerchantDbaName() {
                return merchantDbaName;
            }

            /**
             * Sets the value of the merchantDbaName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMerchantDbaName(String value) {
                this.merchantDbaName = value;
            }

            /**
             * Gets the value of the descriptorText property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescriptorText() {
                return descriptorText;
            }

            /**
             * Sets the value of the descriptorText property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescriptorText(String value) {
                this.descriptorText = value;
            }

            /**
             * Gets the value of the legalCorporateName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLegalCorporateName() {
                return legalCorporateName;
            }

            /**
             * Sets the value of the legalCorporateName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLegalCorporateName(String value) {
                this.legalCorporateName = value;
            }

            /**
             * Gets the value of the brickCount property.
             * 
             */
            public Integer getBrickCount() {
                return brickCount;
            }

            /**
             * Sets the value of the brickCount property.
             * 
             */
            public void setBrickCount(Integer value) {
                this.brickCount = value;
            }

            /**
             * Gets the value of the comment property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getComment() {
                return comment;
            }

            /**
             * Sets the value of the comment property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setComment(String value) {
                this.comment = value;
            }

            /**
             * Gets the value of the locationId property.
             * 
             */
            public Integer getLocationId() {
                return locationId;
            }

            /**
             * Sets the value of the locationId property.
             * 
             */
            public void setLocationId(Integer value) {
                this.locationId = value;
            }

            /**
             * Gets the value of the onlineCount property.
             * 
             */
            public Integer getOnlineCount() {
                return onlineCount;
            }

            /**
             * Sets the value of the onlineCount property.
             * 
             */
            public void setOnlineCount(Integer value) {
                this.onlineCount = value;
            }

            /**
             * Gets the value of the otherCount property.
             * 
             */
            public Integer getOtherCount() {
                return otherCount;
            }

            /**
             * Sets the value of the otherCount property.
             * 
             */
            public void setOtherCount(Integer value) {
                this.otherCount = value;
            }

            /**
             * Gets the value of the soleProprietorName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSoleProprietorName() {
                return soleProprietorName;
            }

            /**
             * Sets the value of the soleProprietorName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSoleProprietorName(String value) {
                this.soleProprietorName = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Line1" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Line2" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
             *         &lt;element name="CountrySubdivision">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="Country">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "line1",
                "line2",
                "city",
                "postalCode",
                "countrySubdivision",
                "country"
            })
            public static class Address {

                @XmlElement(name = "Line1", required = true)
                protected String line1;
                @XmlElement(name = "Line2", required = true)
                protected String line2;
                @XmlElement(name = "City", required = true)
                protected String city;
                @XmlElement(name = "PostalCode")
                protected Integer postalCode;
                @XmlElement(name = "CountrySubdivision", required = true)
                protected CountrySubdivision countrySubdivision;
                @XmlElement(name = "Country", required = true)
                protected Country country;

                /**
                 * Gets the value of the line1 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLine1() {
                    return line1;
                }

                /**
                 * Sets the value of the line1 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLine1(String value) {
                    this.line1 = value;
                }

                /**
                 * Gets the value of the line2 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLine2() {
                    return line2;
                }

                /**
                 * Sets the value of the line2 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLine2(String value) {
                    this.line2 = value;
                }

                /**
                 * Gets the value of the city property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCity() {
                    return city;
                }

                /**
                 * Sets the value of the city property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCity(String value) {
                    this.city = value;
                }

                /**
                 * Gets the value of the postalCode property.
                 * 
                 */
                public Integer getPostalCode() {
                    return postalCode;
                }

                /**
                 * Sets the value of the postalCode property.
                 * 
                 */
                public void setPostalCode(Integer value) {
                    this.postalCode = value;
                }

                /**
                 * Gets the value of the countrySubdivision property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link com.mastercard.api.merchantid.v1.merchantid.domain.MerchantIds.ReturnedMerchants.Merchant.Address.CountrySubdivision }
                 *     
                 */
                public CountrySubdivision getCountrySubdivision() {
                    return countrySubdivision;
                }

                /**
                 * Sets the value of the countrySubdivision property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link com.mastercard.api.merchantid.v1.merchantid.domain.MerchantIds.ReturnedMerchants.Merchant.Address.CountrySubdivision }
                 *     
                 */
                public void setCountrySubdivision(CountrySubdivision value) {
                    this.countrySubdivision = value;
                }

                /**
                 * Gets the value of the country property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link com.mastercard.api.merchantid.v1.merchantid.domain.MerchantIds.ReturnedMerchants.Merchant.Address.Country }
                 *     
                 */
                public Country getCountry() {
                    return country;
                }

                /**
                 * Sets the value of the country property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link com.mastercard.api.merchantid.v1.merchantid.domain.MerchantIds.ReturnedMerchants.Merchant.Address.Country }
                 *     
                 */
                public void setCountry(Country value) {
                    this.country = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "name",
                    "code"
                })
                public static class Country {

                    @XmlElement(name = "Name", required = true)
                    protected String name;
                    @XmlElement(name = "Code", required = true)
                    protected String code;

                    /**
                     * Gets the value of the name property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getName() {
                        return name;
                    }

                    /**
                     * Sets the value of the name property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setName(String value) {
                        this.name = value;
                    }

                    /**
                     * Gets the value of the code property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getCode() {
                        return code;
                    }

                    /**
                     * Sets the value of the code property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setCode(String value) {
                        this.code = value;
                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "name",
                    "code"
                })
                public static class CountrySubdivision {

                    @XmlElement(name = "Name", required = true)
                    protected String name;
                    @XmlElement(name = "Code", required = true)
                    protected String code;

                    /**
                     * Gets the value of the name property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getName() {
                        return name;
                    }

                    /**
                     * Sets the value of the name property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setName(String value) {
                        this.name = value;
                    }

                    /**
                     * Gets the value of the code property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getCode() {
                        return code;
                    }

                    /**
                     * Sets the value of the code property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setCode(String value) {
                        this.code = value;
                    }

                }

            }

        }

    }

}
