//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.10 at 10:29:44 AM CDT 
//


package com.mastercard.api.mdes.csrapi.v1.mapping.search.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Pan" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="AuditInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="UserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Organization" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pan",
    "auditInfo"
})
@XmlRootElement(name = "SearchRequest")
public class SearchRequest {

    @XmlElement(name = "Pan")
    protected long pan;
    @XmlElement(name = "AuditInfo", required = true)
    protected AuditInfo auditInfo;

    /**
     * Gets the value of the pan property.
     * 
     */
    public long getPan() {
        return pan;
    }

    /**
     * Sets the value of the pan property.
     * 
     */
    public void setPan(long value) {
        this.pan = value;
    }

    /**
     * Gets the value of the auditInfo property.
     * 
     * @return
     *     possible object is
     *     {@link com.mastercard.api.mdes.csrapi.v1.mapping.search.domain.SearchRequest.AuditInfo }
     *     
     */
    public AuditInfo getAuditInfo() {
        return auditInfo;
    }

    /**
     * Sets the value of the auditInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.mastercard.api.mdes.csrapi.v1.mapping.search.domain.SearchRequest.AuditInfo }
     *     
     */
    public void setAuditInfo(AuditInfo value) {
        this.auditInfo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="UserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Organization" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userId",
        "userName",
        "organization"
    })
    public static class AuditInfo {

        @XmlElement(name = "UserId", required = true)
        protected String userId;
        @XmlElement(name = "UserName", required = true)
        protected String userName;
        @XmlElement(name = "Organization", required = true)
        protected String organization;

        /**
         * Gets the value of the userId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserId() {
            return userId;
        }

        /**
         * Sets the value of the userId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserId(String value) {
            this.userId = value;
        }

        /**
         * Gets the value of the userName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserName() {
            return userName;
        }

        /**
         * Sets the value of the userName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserName(String value) {
            this.userName = value;
        }

        /**
         * Gets the value of the organization property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrganization() {
            return organization;
        }

        /**
         * Sets the value of the organization property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrganization(String value) {
            this.organization = value;
        }

    }

}
